###
PUT http://localhost:8081/api/storage/teste
Content-Type: application/json

{
    "name": "abc",
    "score": 1
}

###
GET http://localhost:8081/api/storage/teste

###
DELETE http://localhost:8081/api/storage/teste

###
POST http://localhost:8081/api/storage
Content-Type: application/json

{
    "name": "abc",
    "score": 1
}

###
GET http://localhost:8081/api/storage

###
PUT http://localhost:8081/api/queues/q1
Content-Type: application/json

{
    "name": "qqq",
    "change": 0
}

###
GET http://localhost:8081/api/queues/q1
